version: "2.1"
services:
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    networks:
      - traefik_default
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Africa/Cairo
    volumes:
      - config:/config
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.secret.domain`)"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"

networks:
  traefik_default:
    external: true

volumes:
  config: