version: '3'
services:
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    networks:
      - traefik_default
    volumes:
      - /srv/dev-disk-by-label-HD1/configs/Speedtest:/config
    environment:
      - TZ=Africa/Cairo
      - PGID=100
      - PUID=1000
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest.rule=Host(`speedtest.secret.domain`)"
      - "traefik.http.routers.speedtest.tls=true"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"

networks:
  traefik_default:
    external: true