version: "3"

services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=True
      - WATCHTOWER_POLL_INTERVAL=120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock