version: "2.1"
services:
  syncthing:
    image: ghcr.io/linuxserver/syncthing
    container_name: syncthing
    hostname: syncthing
    networks:
      - traefik_default
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Africa/Cairo
    volumes:
      - /srv/dev-disk-by-label-HD1/syncthing/config:/config
      - /srv/dev-disk-by-label-HD1/syncthing:/data1
    ports:
      - 22023:22023
      - 21027:21027/udp
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`syncthing.secret.domain`)"
      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"

networks:
  traefik_default:
    external: true